### ISSUE TITLE
Option not to reorient view when going through portal

### ISSUE THREAD

**Issue by YoukaiTheGit** [Gistix/portal2vr#107]
Feature request to include an option *not* to reorient player view to vertical when traveling through a portal, but to keep the game's native portal-relative orientation (that then gradually reorients to vertical).

Probably not the best idea in terms of motion sickness, but there are probably at least a few players who would enjoy it.

**Comment by lividhen** [comment]
This would be great! I think it might feel a tad less jarring.

**Comment by Audisek** [comment]
No it is a great idea. The instant reorientation doesn't feel immersive for me so I'm waiting for someone to make it an option before I start playing. There's a pull request where people started working on it so I hope it ends up being added.

https://github.com/Gistix/portal2vr/pull/103

**Comment by ORanGeOfficial** [comment]
Here is the fix by [vittorioromeo](https://github.com/vittorioromeo) and [sd805](https://github.com/sd805)

[camUpdate.zip](https://github.com/Gistix/portal2vr/files/13212271/camUpdate.zip)

Overwrite `d3d9.dll` in the `Portal 2\bin` folder and `config.txt` in the `Portal 2\VR` folder.
Also in the `config.txt` you can set `CameraUprightRecoverySpeed` to **0.03** to make the camera rotation speed closer to the original non VR game.

**Comment by YoukaiTheGit** [comment]
Duplicate of #55
