### ISSUE TITLE
I see own dekstop

### ISSUE THREAD

**Issue by nazar123756** [Gistix/portal2vr#121]
Im playing in VR, but in front of me is dekstop screen. Screen is not big, like final cutscene

EDIT:SteamVR Game theater mode need to be disable, but this option was deleted in Steam update. So idk what to do

**Comment by mcitew** [comment]
Too little information given. How do you know start the game ? Did you start with all the commandline option as stated in the GitHub ?

**Comment by nazar123756** [comment]
Yes, i start the game with all launch options via Steam Vr. I can play,
walk, jump... But in front of me dekstop screen.

пн, 18 груд. 2023 р., 04:53 користувач mcitew ***@***.***>
пише:

**Comment by nazar123756** [comment]
SteamVR Game theater mode need to be disable, but this option was deleted in Steam update
