### ISSUE TITLE
Doesn't launch into VR on Linux

### ISSUE THREAD

**Issue by yuckdevchan** [Gistix/portal2vr#133]
When I launch the game it does not launch into VR. Ever.

Headset: Quest 2 w/ ALVR
OS: Bazzite OS
PC: Steam Deck

This could definitely be a bazzite-specific problem as I have encountered a couple of those with steam before.

Any help is appreciated. Looks like a really cool project btw.

**Comment by Tunfisch96** [comment]
I had the same Problem. It woked after I set it to run via Proton and use the Windows  of Portal 2  not the Linux-Native.
