### ISSUE TITLE
(Quest 2) game doesn't do VR even though theatre mode is off and everything is setup correctly

### ISSUE THREAD

**Issue by Schaapie-D2** [Gistix/portal2vr#141]
I am launching the game in steamVR but it does not launch in to VR and when it loads the first scene, it looks down and turns in circles!
And nothing what i do to try to fix it, it doesn't work!!!

**Comment by LolHan** [comment]
Hi! I'm having the same problem, but I already updated my headset :( 
Are you using SteamLink to connect to PC?

**Comment by Schaapie-D2** [comment]
Hi!

Im connecting my headset to my laptop.
Then i open meta quist link.
Then i launch quist link on my headset.
Then i open steam vr on my laptop.
Then i launch portal 2.

**Comment by LolHan** [comment]
Thanks for replying! Unfortunately meta quest link doesn't work on my pc for some reason :(

hopefully ill find another solution
