### ISSUE TITLE
Only loads theater mode, not 360 VR since Virtual Desktop update.

### ISSUE THREAD

**Issue by cykamourn** [Gistix/portal2vr#146]
Was just forced to update Virtual Desktop and it's Streamer. The game now wont load into full 360 VR, it just gives me the theater screen to play on.  In this mode view is tied to the controller.  Am super bummed about this, my son and I both really enjoyed this mod.  Does anyone have any suggestions or a fix for this?

**Comment by DKCTC** [comment]
I am experiencing the same thing, and also on the fork for the Portal Reloaded version. I tried rolling back from 0.2.0-1 to 0.1.5, and it did the same thing.

**Comment by DKCTC** [comment]
ggodin said to update your graphics drivers and restart, which worked for me.

**Comment by cykamourn** [comment]
This worked for me too, thanks!  I tried everything besides updating my gfx drivers, lol.

I'm glad you got ggodin to respond to you beyond "turn off theater mode" cause that's all he'd say to me.
