### ISSUE TITLE
Game always seems to think I'm facing one direction

### ISSUE THREAD

**Issue by zanecodes** [Gistix/portal2vr#2]
I'm unable to interact with buttons unless I'm standing on a particular side of them because the game seems to think I'm always facing the same direction.

This also affects the particle effects that go from the user to the portal reticle when the ASHPD is fired, and may be the reason I'm unable to fire portals onto surfaces that are only large enough to fit one portal on from far away or at an oblique angle (in particular, I'm unable to complete Chapter 4 `The Surprise` because I can't hit the portal target to position the light bridge from across the map, as shown here)

![c04_01](https://github.com/Gistix/portal2vr/assets/1373020/d6f27840-7662-44f9-a1e4-4d10024c36a1)

**Comment by Gistix** [comment]
This should have been fixed in v0.1.1, which version are you using?

**Comment by Mantaray72** [comment]
I have the same problem, latest version.

"I'm unable to interact with buttons unless I'm standing on a particular side of them because the game seems to think I'm always facing the same direction"

Also, almost impossible to look up/down/look at the painting in the first room.

Very difficult to pick up cubes without hands or a pointer.

A sometime game crashes.

I've tried with HP Reverb G2 and Meta Ques2: same problems

**Comment by MarcusInVR** [comment]
Same here. I am unable to place the portal in Chapter 4 "The Surprise", to make the Hard Light Bridge appear and stop one cube from being incinerated. Everything else works, but Portal placement on this one does not - hence making the chamber unsolvable in VR.

**Comment by MoriarVR** [comment]
> This should have been fixed in v0.1.1, which version are you using?

where to find v0.1.1? the link for v0.1 leads to nowhere...

**Comment by Gistix** [comment]
Chamber 18 seems to be having some problems of its own, but the other metioned issues should be fixed in [v0.1.1](https://github.com/Gistix/portal2vr/releases/tag/v0.1.1) (Facing one direction, buttons not working, picking up cubes, looking up and down)

**Comment by zanecodes** [comment]
Thanks! I think the v0.1.1 release was not yet available at the time I wrote this.

**Comment by MarcusInVR** [comment]
It's not closed if it is not working yet ... ? It does not for me. Issue in Chapter 4 remains.
