### ISSUE TITLE
The mod makes Portal 2 not open at all

### ISSUE THREAD

**Issue by TealChipmunk** [Gistix/portal2vr#25]
When I have the mod files where they're supposed to be the game won't even open in flatscreen and sometimes when I try and verify game files it says "All 0 files successfully validated" but it doesn't do this every time. I've copy pasted the launch options. I've deleted  and extracted the mod files into steamapps > common > portal 2 multiple times. I've told steam not to use the theater I've also tried uninstalling and reinstalling the game as well as installing it onto my SSD instead of my HDD but still the same thing happens: I press play, it loads for a few seconds, says running and then stops and the play button appears again. But as soon as i uninstall the mod files it loads up properly into flatscreen. I have an hp reverb g2 if that's the problem.

Update
I got it working I'm not entirely sure how but restarting my pc was the last thing i tried before it worked.

**Comment by iam4k33m** [comment]
Afaik it **needs** SteamVR to run as this mod uses OpenVR, not OpenXR like has become standard. You can use [Windows Mixed Reality For SteamVR](https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/) to bridge between your WMR headset and SteamVR

**Comment by TealChipmunk** [comment]
> Afaik it **needs** SteamVR to run as this mod uses OpenVR, not OpenXR like has become standard. You can use [Windows Mixed Reality For SteamVR](https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/) to bridge between your WMR headset and SteamVR

yea i probably should have said that i have and use windows mixed reality for steamVR in my first post. my bad

**Comment by dotheboogey678** [comment]
you fixed it yet?

**Comment by TealChipmunk** [comment]
> you fixed it yet?

No not yet I'm assuming its something to do with WMR simply not working with the mod. The mod will probably have to be updated to support WMR somehow. But I'll keep trying things and if I find a fix I'll update here

**Comment by dotheboogey678** [comment]
> > you fixed it yet?
> 
> No not yet I'm assuming its something to do with WMR simply not working with the mod. The mod will probably have to be updated to support WMR somehow. But I'll keep trying things and if I find a fix I'll update here

for me when i rename openvr_api to smt else it launches

**Comment by TealChipmunk** [comment]
> > > you fixed it yet?
> > 
> > 
> > No not yet I'm assuming its something to do with WMR simply not working with the mod. The mod will probably have to be updated to support WMR somehow. But I'll keep trying things and if I find a fix I'll update here
> 
> for me when i rename openvr_api to smt else it launches

I've just tried this and it opens the game just not in vr

**Comment by dotheboogey678** [comment]
> > > > you fixed it yet?
> > > 
> > > 
> > > No not yet I'm assuming its something to do with WMR simply not working with the mod. The mod will probably have to be updated to support WMR somehow. But I'll keep trying things and if I find a fix I'll update here
> > 
> > 
> > for me when i rename openvr_api to smt else it launches
> 
> I've just tried this and it opens the game just not in vr

yea so idk tbh

**Comment by dotheboogey678** [comment]
> > > > you fixed it yet?
> > > 
> > > 
> > > No not yet I'm assuming its something to do with WMR simply not working with the mod. The mod will probably have to be updated to support WMR somehow. But I'll keep trying things and if I find a fix I'll update here
> > 
> > 
> > for me when i rename openvr_api to smt else it launches
> 
> I've just tried this and it opens the game just not in vr

new verison came out

**Comment by iam4k33m** [comment]
After spelunking I've found that the game will _exit_ if it is launched without the -insecure flag. It could be this?

**Comment by dotheboogey678** [comment]
> After spelunking I've found that the game will _exit_ if it is launched without the -insecure flag. It could be this?

thats werid

**Comment by iam4k33m** [comment]
I suspect it's a leftover from L4DVR, which enforced insecure for vac reasons. I'll probs make a PR later

**Comment by TealChipmunk** [comment]
> After spelunking I've found that the game will _exit_ if it is launched without the -insecure flag. It could be this?

Doesn't seem to be the problem for me cuz the first launch option is -insecure

**Comment by J-Emil-P** [comment]
Did you add the flags in steam or in the desktop shortcut?
Right click game > properties > add your flags in the field at the bottom

**Comment by TealChipmunk** [comment]
> Did you add the flags in steam or in the desktop shortcut? Right click game > properties > add your flags in the field at the bottom

In launch options? If so ya I've done that

**Comment by thesockmonster2** [comment]
I'm having the same issue. Using a Lenovo Explorer with WMR for SteamVR. please let me know if you find a way to get it working.

**Comment by TealChipmunk** [comment]
> I'm having the same issue. Using a Lenovo Explorer with WMR for SteamVR. please let me know if you find a way to get it working.

I've gotten it working not sure what it was but the last thing i did before it started working was I restarted my pc but I've also seen some people saying that it didn't fix it for them so i don't know
