### ISSUE TITLE
When cube is dropped game crashes

### ISSUE THREAD

**Issue by Rilzz110** [Gistix/portal2vr#3]
im the second chamber of the second chapter, i tried to pick up the cube and it disappeared but the portal gun was still acting as if there was still a cube being held. I tried dropping the cube and the game crashed.

**Comment by pelegshalev** [comment]
I picked up a turret in a save, immediately crashed. Shame because it looked so fucking cool and felt awesome, hope for an update soon

**Comment by HexHyte** [comment]
> I picked up a turret in a save, immediately crashed.

The same happened to me whil in a Community map I've created

**Comment by HexHyte** [comment]
> > I picked up a turret in a save, immediately crashed.
> 
> The same happened to me while playing a Community map I've created in the past

The issue has been resolved with v.0.1.1

**Comment by Gistix** [comment]
As mentioned previously this issue has been fixed in v0.1.1
