### ISSUE TITLE
No 6DoF

### ISSUE THREAD

**Issue by zai-tm** [Gistix/portal2vr#31]
For some reason, when I move my head around, the camera stays in the same spot. It's a little disorienting.

**Comment by foliagecanine** [comment]
Did you set 6DOF=true in steamapps/common/Portal 2/VR/config.txt?

**Comment by zai-tm** [comment]
Oh thanks

**Comment by benjamincheng10** [comment]
oh why is it 3Dof by default?

**Comment by Derpalus** [comment]
^This. Also if it has to be 3Dof by default, why isn't it mentioned in the readme? Pretty much 100% of the users are going to run into this completely undocumented "feature".

**Comment by nwalmethule** [comment]
I have the same issue, please include this "detail" in the read me, thanks.
