### ISSUE TITLE
No laser pointer nor crosshair in sight

### ISSUE THREAD

**Issue by Audisek** [Gistix/portal2vr#41]
Hi, I'm on Quest 2 - Virtual Desktop - SteamVR.

I have no crosshair nor laser pointer, so I have no way of precisely aiming with the portal gun.

I only have the pointer when in the pause menu.

Any ideas how to enable any of them?

Also, is there a Discord server for this mod?

**Comment by foliagecanine** [comment]
They should be enabled by default.
Check your steamapps/common/Portal 2/VR/config.txt and make sure AimMode is 1 or 2. 

Discord is here: [flat2vr.com](flat2vr.com). join using Portal 2 VR mod category in the #p2-join channel

**Comment by Audisek** [comment]
It was already on 2 by default.

Still couldn't make anything show up.

I've tried every combination of:
Oculus AirLink / Virtual Desktop
OpenXR runtime: Oculus / SteamVR
AimMode: 1 / 2
Opening SteamVR first / running the game without SteamVR running first.

My PC is:
Windows 11
5800X3D
RTX 3080
Latest Nvidia drivers, 537.34

Anyone else has the same issue as me?

**Comment by nayutune** [comment]
crosshair option in-game must be on in order for either to show up.
You can use developer console to set 'crosshair 1'

**Comment by Audisek** [comment]
I did a fresh Portal 2 install so I'd be surprised if it was at 0, but I'll make sure later today after work.

**Comment by Audisek** [comment]
ok it was the 'crosshair 0' cvar.

But I have no idea why it was on zero, I'd never change that.

**Comment by flashman1986** [comment]
I have same problem in portal stories mel. I use same setting in config as the man in this video ( https://youtu.be/gtcDlPodb5o?si=eI46VDKkGNaM1AIG ) Laser and Crosshair does not appear, crosshair is set to 1
