### ISSUE TITLE
Snap Turn Support

### ISSUE THREAD

**Issue by mhalttu** [Gistix/portal2vr#43]
Please add support for snap turning. This is quite standard in most VR games, and should make it less likely that you'll get motion sickness. For example a 30 degree angle per turn might be a good default.

**Comment by Audisek** [comment]
set it to 'true' in the VR\config.txt file

**Comment by Maks7594** [comment]
> Oh, great. Thank you! Should I close this request? Or would it still be helpful to point people to the `config.txt` file in the documentation?

close this request, it means that your issue has been solved. for people looking for snap turn? it's in steamapps/common/Portal 2/VR/config.txt and set SnapTurning to true
