### ISSUE TITLE
headset only has 3Dof tracking

### ISSUE THREAD

**Issue by benjamincheng10** [Gistix/portal2vr#51]
When playing on my headset, i only have 3Dof tracking while the Portal gun has full 6Dof. Really wierd

**Comment by HexHyte** [comment]
Duplicate of https://github.com/Gistix/portal2vr/issues/31

set 6DOF=true
in
steamapps/common/Portal 2/VR/config.txt

**Comment by J-Emil-P** [comment]
@benjamincheng10 remember to close the issue if it was fixed

**Comment by jurassicjordan** [comment]
Why is that config disabled by default?
