### ISSUE TITLE
crashes after loading please fix

### ISSUE THREAD

**Issue by GordonFreemanisreal** [Gistix/portal2vr#56]
literally happening to everyone

**Comment by programmer2514** [comment]
The issue has already been reported, and only 8 hours ago it seems. It does not need to be spammed in a rude tone. These devs have put in an enormous amount of work to make this mod even exist, and are not charging you a cent. It takes time to fix a bug, and if you think you can do it better, go right ahead. Otherwise have some patience and respect and let the devs develop.

**Comment by dvdgitman** [comment]
this is why we cant have nice things

**Comment by ROOROO03** [comment]
ive been following this mod since they it was announced but its annoying that they have released it in an unplayable state, also no one asked furry

**Comment by programmer2514** [comment]
> its annoying that they have released it in an unplayable state

I mean they could have just not released it at all, that's the alternative

> also no one asked furry

LMAO 10/10 insult, you got me, brings me right back to middle school

**Comment by ROOROO03** [comment]
so you just proved my point lmao

**Comment by programmer2514** [comment]
XD? That you're immature? I think you proved that. Anyways, I have better things to do than arguing with a salty 13yo on github LOL

**Comment by imcommonsense** [comment]
i'm confused about this.

mod loads fine for me, although i've been using it on Portal Stories: Mel.
wonder if it's something specifically in portal.


and for OP:
stop being an asshole. these devs work for free to provide you with something lovely.
also, who cares if programmer2514 is a furry? legit nothing wrong with that
would you like someone to make total fun of you for enjoying gaming?
you should probably get off github mate. you're probably too young to be on here.

**Comment by ROOROO03** [comment]
> XD? That you're immature? I think you proved that. Anyways, I have better things to do than arguing with a salty 13yo on github LOL

okay then

**Comment by ROOROO03** [comment]
> i'm confused about this.
> 
> mod loads fine for me, although i've been using it on Portal Stories: Mel. wonder if it's something specifically in portal.
> 
> and for OP: stop being an asshole. these devs work for free to provide you with something lovely. also, who cares if programmer2514 is a furry? legit nothing wrong with that would you like someone to make total fun of you for enjoying gaming? you should probably get off github mate. you're probably too young to be on here.

just because I called them a furry which they literally are doesn't mean I'm 5 years old, its not my fault me and a bunch of other people cant play it, we are waiting for a fix

**Comment by imcommonsense** [comment]
did you know your mouse a scroll wheel? you can scroll down to the second most recent build, which functions perfectly fine by the way!

**Comment by GordonFreemanisreal** [comment]
> did you know your mouse a scroll wheel? you can scroll down to the second most recent build, which functions perfectly fine by the way!

well when I made this yesterday it didn't have a 'new version' so there we go
