### ISSUE TITLE
Portal 2 Opening just not in vr 

### ISSUE THREAD

**Issue by MrCharChar** [Gistix/portal2vr#60]
When I open portal 2 with steam vr open before it, it still just opens regularly

**Comment by vilj0pr0gamer** [comment]
same here

**Comment by Aerotactics** [comment]
Go to the game properties and make sure this option is disabled
![image](https://github.com/Gistix/portal2vr/assets/60725574/9e4a12d6-3aa4-4592-a0c2-c1da55d3c9ae)

**Comment by MrCharChar** [comment]
> Go to the game properties and make sure this option is disabled
> 
> ![image](https://github.com/Gistix/portal2vr/assets/60725574/9e4a12d6-3aa4-4592-a0c2-c1da55d3c9ae)
> 
> 

That still didn't work

**Comment by Aerotactics** [comment]
> > Go to the game properties and make sure this option is disabled
> > ![image](https://user-images.githubusercontent.com/60725574/269437117-9e4a12d6-3aa4-4592-a0c2-c1da55d3c9ae.png)
> 
> That still didn't work

Did you setup the launch options?

**Comment by vilj0pr0gamer** [comment]
yes

**Comment by vilj0pr0gamer** [comment]
> > Go to the game properties and make sure this option is disabled
> > ![image](https://user-images.githubusercontent.com/60725574/269437117-9e4a12d6-3aa4-4592-a0c2-c1da55d3c9ae.png)
> 
> That still didn't work

same

**Comment by MrCharChar** [comment]
> > > Go to the game properties and make sure this option is disabled
> 
> > > ![image](https://user-images.githubusercontent.com/60725574/269437117-9e4a12d6-3aa4-4592-a0c2-c1da55d3c9ae.png)
> 
> > 
> 
> > That still didn't work
> 
> 
> 
> Did you setup the launch options?

Yeah still didn't work

**Comment by J-Cott** [comment]
Yes I just get the message when trying to launch it with Steam VR connected, it just says "Portal 2 does not support VR. It will appear on your desktop and may affect VR performance" anyone know how to fix this?

**Comment by ciriguaya** [comment]
I'm stuck on the same issue, please can someone help. Thx

**Comment by SneakySpaceCat** [comment]
"Portal 2 does not support VR. It will appear on your desktop and may affect VR performance" anyone know how to fix this?"

I was having the same issue. I copied the 3 files that came in the extracted Portal2VR folder and pasted them I to the Portal 2 directory.

**Comment by ciriguaya** [comment]
ok so just a restart helped with solving that issue. hope that helps

**Comment by MrCharChar** [comment]
> ok so just a restart helped with solving that issue. hope that helps

I had this issue 2 days ago and have restarted and turned off my computer multiple times and it still doesn't work

**Comment by rgrocott** [comment]
I get that warning, and the game initially opens on my monitor (not in VR), but when I start an actual game (with Steam VR already active) then it goes into VR mode and I can play.

**Comment by Juliasmatius** [comment]
Are there folders called portal2_dlc3 and VR in the portal 2 main folder?

**Comment by jasonridesabike** [comment]
the option referenced as a fix no longer seems to exist in steamvr2

**Comment by MrCharChar** [comment]
I extracted the vr folder in the wrong place oops 😭
