### ISSUE TITLE
Game crashes when starting any level or chapter

### ISSUE THREAD

**Issue by DatGamer56** [Gistix/portal2vr#64]
Portal 2 boots up fine, windowed on flatscreen and vr, and then crashes when I try to play the courtesy call or workshop levels

I've tried disabling antivirus, no luck
Verified files, no luck

**Comment by ProtatoGamer64** [comment]
Same issue. Cant find a solution

**Comment by HexHyte** [comment]
Does it crash even if you try to start a new game?

**Comment by DatGamer56** [comment]
> Does it crash even if you try to start a new game?

Yep, crashes when I try to load any level
Oh and it also crashes when I change any video settings

**Comment by Decoder0007** [comment]
Do you have an AMD graphics card?

**Comment by DatGamer56** [comment]
> Do you have an AMD graphics card?

I have a NVIDIA GeForce RTX 2060

**Comment by Decoder0007** [comment]
> I have a NVIDIA GeForce RTX 2060

Do you have OVERWOLF installed by any chance?

**Comment by DatGamer56** [comment]
> Do you have OVERWOLF installed by any chance?

I used to have OVERWOLF but uninstalled it about a year ago

**Comment by Decoder0007** [comment]
> I used to have OVERWOLF but uninstalled it about a year ago

Do you have any other overlays like overwolf?

**Comment by DatGamer56** [comment]
> > I used to have OVERWOLF but uninstalled it about a year ago
> 
> Do you have any other overlays like overwolf?

The only overlays I can think of is either Steam or GeForce Experience

**Comment by Decoder0007** [comment]
Can you try and disable GeForce experience. If possible uninstall it
temporarily

**Comment by DatGamer56** [comment]
> Can you try and disable GeForce experience. If possible uninstall it temporarily

Disabled overlay in settings and tried uninstalling completely, no luck.

**Comment by Decoder0007** [comment]
Just to confirm. It does get to the menu and then crashes after about 10
seconds?

**Comment by DatGamer56** [comment]
Found the issue. Idk how I didn't realize this but SAR was causing the issue, along with srconfigs.
