### ISSUE TITLE
Game Doesn't Launch In Vr

### ISSUE THREAD

**Issue by Thetvgamer** [Gistix/portal2vr#78]
The Game launches on my computer but steam VR doesn't pick up on it, I'm pretty sure I've done everything right but if i have not, please tell me what I did wrong! Btw the game does launch on my computer and i can hear audio.
![image](https://github.com/Gistix/portal2vr/assets/130416750/f353735a-b4d8-4e1f-9b0c-cf07d814f08e)
![image](https://github.com/Gistix/portal2vr/assets/130416750/ede4eb56-7aca-49e9-8e02-27549bfdf367)

**Comment by devsnd** [comment]
You are supposed to copy the contents of the `Portal2VR` folder into the game folder, not the folder itself.

**Comment by Thetvgamer** [comment]
I figured that out shortly after I posted this and forgot to close it, but this is really helpful, thanks!
