### ISSUE TITLE
Pressing down on left joystick opens steam menu instead of resetting camera height

### ISSUE THREAD

**Issue by ArcdoesMC** [Gistix/portal2vr#82]
Whenever I try to reset the camera height by pressing down on the left thumbstick, it just pulls up the steam menu. How do I reset the camera height so I don't have to play laying down on my stomach to get close to the correct height and not be 12 feet tall? If I'm an idiot and this is a simple issue to solve I will be more than happy.

**Comment by programmer2514** [comment]
Try out [OVR Advanced Settings](https://store.steampowered.com/app/1009850/OVR_Advanced_Settings/). It lets you move your playspace around to wherever you want without affecting virtual boundaries.

**Comment by ArcdoesMC** [comment]
That fixed it, I don't know know if the developer was talking about that and forgot it was a thirds part install or not. But its been a fantastic experience once I got through that.

**Comment by ArcdoesMC** [comment]
Compl
