### ISSUE TITLE
Portal gun missing bottom

### ISSUE THREAD

**Issue by TheIdiot0** [Gistix/portal2vr#83]
The bottom of the portal gun is just.. gone. Is this normal? I'm pretty sure its the og model, which is missing parts you don't see, is there supposed to be a custom one or is this some weird bug?

**Comment by MadelineMaid** [comment]
no custom one, just uses the base gun model im pretty sure

**Comment by Clara81221** [comment]
It's the same for me, I think it's just something that's not implemented. As MadelineMaid said, it should just use the base gun model, which hides what you don't see as you said. Maybe at some point they'll include a custom model!

**Comment by devsnd** [comment]
This is the same issue as #47. I'd suggest to close this one if you don't mind @TheIdiot0

**Comment by TheIdiot0** [comment]
Yea, just came back while later to this mod, remembered I had this, now i'm writing this.

**Comment by TheIdiot0** [comment]
Closing..

**Comment by TheIdiot0** [comment]
For anyone wondering, go to the flat2vr discord, https://discord.com/invite/ZFSCSDe , and go to p2 join, click toggle channels, go to p2 general, go to threads, and click on  Portal 2 vr HD portal gun, and find the user Deleted user  and download what ever fixed portal gun you want. No hands is just the gun, 1 hand has chell's hand holding the handle, and two hands has both hands (its not like in vr shooter games where the end of the gun is attached to your non-dominant hand, its just a model.) YW!
