### ISSUE TITLE
[Non-issue] Could this be worked into a Portal 1 VR mod?

### ISSUE THREAD

**Issue by Clara81221** [Gistix/portal2vr#85]
Seeing as this is already forked from L4D2VR, it must work with other source games, given tweaking. Would the original Portal work? It'd also be closer to the original HL2 code...

**Comment by Flux001337** [comment]
> Portal 1 VR mod is essentially done, but unlike this mod, 
> it's built on the Portal SDK which Valve hasn't given specific permission to us to release yet unfortunately :-(

[Source](https://twitter.com/Flat2VR/status/1703124061260267586?s=20)

**Comment by Clara81221** [comment]
Oh wow, that's quite impressive actually. I had no idea the portal 1 vr mod was even in development. Hopefully valve gives them permission soon.

**Comment by ghost** [comment]
2025 still no portal 1 vr
